import { pool } from "./db";
import { HISTORY_PAGE_SIZE } from "./appConfig";
import type { LearnerMemory, LearnerHistoryEntry, LearningPath } from "./types";

interface HistoryRow {
  id: string;
  topic: string;
  occurred_at: string;
  language: string | null;
  subject: string | null;
  score_percent: number | null;
  strong_areas: string[];
  weak_areas: string[];
  recommendation: string | null;
  transcript: LearnerHistoryEntry["transcript"];
  quiz: LearnerHistoryEntry["quiz"];
}

function rowToEntry(row: HistoryRow): LearnerHistoryEntry {
  return {
    id: row.id,
    topic: row.topic,
    date: row.occurred_at,
    language: row.language ?? "",
    subject: row.subject ?? undefined,
    scorePercent: row.score_percent ?? undefined,
    strongAreas: row.strong_areas ?? [],
    weakAreas: row.weak_areas ?? [],
    recommendation: row.recommendation ?? undefined,
    transcript: row.transcript ?? [],
    quiz: row.quiz ?? [],
  };
}

/**
 * Derives per-concept mastery from lesson history (M1).
 *
 * The rule is "the most recent lesson that mentioned a concept decides it".
 * The previous implementation did not implement that rule: walking
 * newest-first, it added weaknesses to a set and then, for every entry
 * including *older* ones, ran `weak.delete(s)` for each strong area. An older
 * lesson where a concept went well therefore erased a newer lesson where it
 * went badly, and the weakness silently disappeared from the dashboard and
 * from the remediation the learner was offered.
 *
 * Now the first mention wins outright: once a concept is decided, older
 * entries cannot change it. Within a single entry, a concept listed as both
 * strong and weak resolves to weak — the conservative reading, since the cost
 * of revisiting a concept the learner knows is far lower than dropping one
 * they do not.
 *
 * `history` must be ordered newest-first.
 */
export function deriveConceptMastery(
  // Both lists are optional: rows written before these columns existed, and
  // rows that recorded only one side, are read back with the field missing.
  history: { strongAreas?: string[]; weakAreas?: string[] }[]
): { strongConcepts: string[]; weakConcepts: string[] } {
  const decided = new Map<string, "strong" | "weak">();

  for (const entry of history) {
    for (const concept of entry.weakAreas ?? []) {
      if (!decided.has(concept)) decided.set(concept, "weak");
    }
    for (const concept of entry.strongAreas ?? []) {
      if (!decided.has(concept)) decided.set(concept, "strong");
    }
  }

  const strongConcepts: string[] = [];
  const weakConcepts: string[] = [];
  for (const [concept, verdict] of decided) {
    (verdict === "strong" ? strongConcepts : weakConcepts).push(concept);
  }
  return { strongConcepts, weakConcepts };
}

export async function loadMemoryForUser(userId: number): Promise<LearnerMemory> {
  const { rows } = await pool.query<HistoryRow>(
    `SELECT id, topic, occurred_at, language, subject, score_percent,
            strong_areas, weak_areas, recommendation, transcript, quiz
     FROM learner_history_entries
     WHERE user_id = $1
     ORDER BY occurred_at DESC
     LIMIT $2`,
    [userId, HISTORY_PAGE_SIZE]
  );
  const history = rows.map(rowToEntry);

  // M2: only the most recent HISTORY_PAGE_SIZE lessons are loaded, so the
  // total is reported alongside them. Without it the dashboard presented a
  // windowed count and average as though they covered the whole account.
  const countResult = await pool.query<{ count: string }>(
    `SELECT count(*)::text AS count FROM learner_history_entries WHERE user_id = $1`,
    [userId]
  );
  const historyTotal = Number(countResult.rows[0]?.count ?? history.length);

  const { strongConcepts, weakConcepts } = deriveConceptMastery(history);

  const pathResult = await pool.query<{ path: LearningPath; current_step_index: number }>(
    `SELECT path, current_step_index FROM learner_learning_path WHERE user_id = $1`,
    [userId]
  );
  const pathRow = pathResult.rows[0];

  return {
    history,
    weakConcepts,
    strongConcepts,
    historyTotal,
    historyWindow: HISTORY_PAGE_SIZE,
    currentPath: pathRow?.path,
    currentStepIndex: pathRow?.current_step_index,
  };
}

export interface SavedHistoryEntry {
  id: string;
  /** True when this id was already stored — a retry, not a second lesson. */
  replayed: boolean;
}

/**
 * Writes one completed lesson, idempotently (H7).
 *
 * The id is generated by the client, so retrying a request that timed out
 * used to hit the primary key and fail with a 500 — which made a safe retry
 * look like a new error. `ON CONFLICT DO NOTHING` turns the second write into
 * a no-op, and the follow-up check makes sure a replay is really the same
 * owner's row rather than a collision with someone else's id.
 */
export async function addHistoryEntryForUser(
  userId: number,
  entry: LearnerHistoryEntry
): Promise<SavedHistoryEntry> {
  const inserted = await pool.query(
    `INSERT INTO learner_history_entries
       (id, user_id, topic, occurred_at, language, subject, score_percent,
        strong_areas, weak_areas, recommendation, transcript, quiz)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
     ON CONFLICT (id) DO NOTHING
     RETURNING id`,
    [
      entry.id,
      userId,
      entry.topic,
      entry.date,
      entry.language ?? null,
      entry.subject ?? null,
      entry.scorePercent ?? null,
      JSON.stringify(entry.strongAreas ?? []),
      JSON.stringify(entry.weakAreas ?? []),
      entry.recommendation ?? null,
      JSON.stringify(entry.transcript ?? []),
      JSON.stringify(entry.quiz ?? []),
    ]
  );
  if (inserted.rows.length > 0) return { id: entry.id, replayed: false };

  const existing = await pool.query<{ user_id: number }>(
    `SELECT user_id FROM learner_history_entries WHERE id = $1`,
    [entry.id]
  );
  const owner = existing.rows[0]?.user_id;
  if (owner !== userId) {
    // Two learners cannot legitimately generate the same UUID, so this is a
    // crafted id rather than an accident. Refuse rather than report success.
    throw new HistoryIdConflict();
  }
  return { id: entry.id, replayed: true };
}

/** Raised when a history id is already in use by a different account. */
export class HistoryIdConflict extends Error {
  constructor() {
    super("That history entry id is already in use.");
    this.name = "HistoryIdConflict";
  }
}

export async function setCurrentPathForUser(
  userId: number,
  path: LearningPath,
  stepIndex: number
): Promise<void> {
  await pool.query(
    `INSERT INTO learner_learning_path (user_id, path, current_step_index)
     VALUES ($1, $2, $3)
     ON CONFLICT (user_id) DO UPDATE SET path = $2, current_step_index = $3, updated_at = now()`,
    [userId, JSON.stringify(path), stepIndex]
  );
}

export interface PathAdvance {
  stepIndex: number;
  /** False when the command was a replay or arrived out of order. */
  advanced: boolean;
}

/**
 * Advances the learner one step, but only from the step they were on (H8).
 *
 * Two bugs lived in the old one-line UPDATE. It clamped with
 * `jsonb_array_length(path->'steps')`, one *past* the last valid index, so
 * finishing the final step left the path pointing at a step that does not
 * exist and the dashboard showed nothing active. And it advanced
 * unconditionally, so a duplicate completion, a delayed retry or a lesson
 * that had nothing to do with the path all pushed progress forward and
 * skipped steps.
 *
 * `fromStepIndex` is the step the finished lesson belonged to. The UPDATE
 * only matches while the stored index still equals it, which makes the
 * command idempotent: the second copy of the same completion changes nothing
 * and reports the position rather than failing.
 */
export async function advancePathForUser(
  userId: number,
  fromStepIndex: number
): Promise<PathAdvance> {
  const advanced = await pool.query<{ current_step_index: number }>(
    `UPDATE learner_learning_path
        SET current_step_index = LEAST(
              $2::int + 1,
              GREATEST(jsonb_array_length(path -> 'steps') - 1, 0)
            ),
            updated_at = now()
      WHERE user_id = $1 AND current_step_index = $2::int
      RETURNING current_step_index`,
    [userId, fromStepIndex]
  );
  if (advanced.rows.length > 0) {
    return { stepIndex: advanced.rows[0].current_step_index, advanced: true };
  }

  const current = await pool.query<{ current_step_index: number }>(
    `SELECT current_step_index FROM learner_learning_path WHERE user_id = $1`,
    [userId]
  );
  const row = current.rows[0];
  if (!row) throw new NoActivePath();
  return { stepIndex: row.current_step_index, advanced: false };
}

/** Raised when a learner with no saved path asks to advance it. */
export class NoActivePath extends Error {
  constructor() {
    super("There is no active learning path to advance.");
    this.name = "NoActivePath";
  }
}
